--CREATE TABLES

CREATE TABLE TB_CATEGORY(
    ID_CATEGORY INT PRIMARY KEY AUTO_INCREMENT,
    NM_CATEGORY VARCHAR(50) NOT NULL
);

CREATE TABLE TB_PRODUCT(
	ID_PRODUCT INT PRIMARY KEY AUTO_INCREMENT,
	NM_PRODUCT VARCHAR(50) NOT NULL,
	VL_PRODUCT DECIMAL(10, 2) NOT NULL,
	ID_CATEGORY INT NOT NULL,
	FOREIGN KEY(ID_CATEGORY) REFERENCES TB_CATEGORY(ID_CATEGORY)
);

CREATE TABLE TB_TABLE (
	ID_TABLE INT PRIMARY KEY AUTO_INCREMENT,
	NM_TABLE VARCHAR(50) NOT NULL
);

CREATE TABLE TB_ORDER_ADDRESS (
	ID_ORDER_ADDRESS BIGINT PRIMARY KEY AUTO_INCREMENT,
	NM_CLIENT VARCHAR(255) NOT NULL,
	NM_STREET VARCHAR(255) NOT NULL,
	NR_NUMBER VARCHAR(6),
	DS_COMPLEMENT VARCHAR(20),
	NM_DISTRICT VARCHAR(30) NOT NULL,
	NM_CITY VARCHAR NOT NULL,
	NM_STATE VARCHAR(30) NOT NULL
);

CREATE TABLE TB_ORDER_STATUS (
	ID_ORDER_STATUS INT PRIMARY KEY,
	DS_ORDER_STATUS VARCHAR(20)
);

INSERT INTO 
	TB_ORDER_STATUS (
		ID_ORDER_STATUS, 
		DS_ORDER_STATUS)
VALUES 
	(1,'COMPLETE'),
	(2,'DOING'),
	(3,'CANCELED'),
	(4,'DELIVERED');

CREATE TABLE TB_ORDER_TYPE (
	ID_ORDER_TYPE INT PRIMARY KEY,
	DS_ORDER_TYPE VARCHAR(20)
);

INSERT INTO 
	TB_ORDER_TYPE (
		ID_ORDER_TYPE, 
		DS_ORDER_TYPE)
VALUES 
	(1,'DELIVERY'),
	(2,'TABLE'),
	(3,'DESK');

CREATE TABLE TB_ORDER (
	ID_ORDER BIGINT PRIMARY KEY AUTO_INCREMENT,
	DT_ORDER DATE NOT NULL,
	VL_ORDER DECIMAL(8, 2) NOT NULL,
	VL_DELIVERY DECIMAL(8, 2),
	ID_ORDER_STATUS INT NOT NULL,
	ID_ORDER_TYPE INT NOT NULL,
	ID_ORDER_ADDRESS BIGINT,
	FOREIGN KEY(ID_ORDER_STATUS) REFERENCES TB_ORDER_STATUS(ID_ORDER_STATUS),
	FOREIGN KEY(ID_ORDER_TYPE) REFERENCES TB_ORDER_TYPE(ID_ORDER_TYPE),
	FOREIGN KEY(ID_ORDER_ADDRESS) REFERENCES TB_ORDER_ADDRESS(ID_ORDER_ADDRESS)
);

CREATE TABLE TB_ORDER_ITEM (
	ID_ORDER_ITEM BIGINT PRIMARY KEY AUTO_INCREMENT,
	ID_PRODUCT INT NOT NULL,
	ID_ORDER BIGINT NOT NULL,
	QT_ORDER_ITEM SMALLINT NOT NULL,
	VL_ORDER_ITEM DECIMAL(8, 2) NOT NULL,
	FOREIGN KEY(ID_PRODUCT) REFERENCES TB_PRODUCT(ID_PRODUCT),
	FOREIGN KEY(ID_ORDER) REFERENCES TB_ORDER(ID_ORDER)
);





