--CREATE TABLES

CREATE TABLE TB_CATEGORY(
    ID_CATEGORY INT PRIMARY KEY AUTO_INCREMENT,
    NM_CATEGORY VARCHAR(50) NOT NULL
);

CREATE TABLE TB_PRODUCT(
	ID_PRODUCT INT PRIMARY KEY AUTO_INCREMENT,
	NM_PRODUCT VARCHAR(50) NOT NULL,
	VL_PRODUCT DECIMAL(10, 2) NOT NULL,
	ID_CATEGORY INT NOT NULL,
	FOREIGN KEY(ID_CATEGORY) REFERENCES TB_CATEGORY(ID_CATEGORY)
);