--CREATE TABLES

CREATE TABLE TB_CATEGORY(
    ID_CATEGORY INT PRIMARY KEY AUTO_INCREMENT,
    NM_CATEGORY VARCHAR(50) NOT NULL
);

CREATE TABLE TB_PRODUCT(
	ID_PRODUCT INT PRIMARY KEY AUTO_INCREMENT,
	NM_PRODUCT VARCHAR(50) NOT NULL,
	VL_PRODUCT DECIMAL(10, 2) NOT NULL,
	ID_CATEGORY INT NOT NULL,
	FOREIGN KEY(ID_CATEGORY) REFERENCES TB_CATEGORY(ID_CATEGORY)
);

CREATE TABLE TB_TABLE (
	ID_TABLE INT PRIMARY KEY AUTO_INCREMENT,
	NM_TABLE VARCHAR(50) NOT NULL
);

CREATE TABLE TB_ORDER_ADDRESS (
	ID_ORDER_ADDRESS INT PRIMARY KEY AUTO_INCREMENT,
	NM_STREET VARCHAR(255) NOT NULL,
	NR_NUMBER VARCHAR(6),
	DS_COMPLEMENT VARCHAR(20),
	NM_DISTRICT VARCHAR(30) NOT NULL,
	NM_CITY VARCHAR NOT NULL,
	NM_STATE VARCHAR(30) NOT NULL
);